--INSERTS COUNTRIES ISO CODES

INSERT INTO countries (isocode, name, alfaisotwo, alfaisothree) VALUES ('004', 'Afganistan', 'AF', 'AFG');
INSERT INTO countries (isocode, name, alfaisotwo, alfaisothree) VALUES ('008', 'Albania', 'AL', 'ALB');
INSERT INTO countries (isocode, name, alfaisotwo, alfaisothree) VALUES ('276', 'Alemania', 'DE', 'DEU');
INSERT INTO countries (isocode, name, alfaisotwo, alfaisothree) VALUES ('020', 'Andorra', 'AD', 'AND');
INSERT INTO countries (isocode, name, alfaisotwo, alfaisothree) VALUES ('024', 'Angola', 'AO', 'AGO');
INSERT INTO countries (isocode, name, alfaisotwo, alfaisothree) VALUES ('660', 'Anguilla', 'AI', 'AIA');
INSERT INTO countries (isocode, name, alfaisotwo, alfaisothree) VALUES ('010', 'Antartida', 'AQ', 'ATA');
INSERT INTO countries (isocode, name, alfaisotwo, alfaisothree) VALUES ('028', 'Antigua y Barbuda', 'AG', 'ATG');
INSERT INTO countries (isocode, name, alfaisotwo, alfaisothree) VALUES ('682', 'Arabia Saudi', 'SA', 'SAU');
INSERT INTO countries (isocode, name, alfaisotwo, alfaisothree) VALUES ('012', 'Argelia', 'DZ', 'DZA');
INSERT INTO countries (isocode, name, alfaisotwo, alfaisothree) VALUES ('032', 'Argentina', 'AR', 'ARG');
INSERT INTO countries (isocode, name, alfaisotwo, alfaisothree) VALUES ('051', 'Armenia', 'AM', 'ARM');
INSERT INTO countries (isocode, name, alfaisotwo, alfaisothree) VALUES ('533', 'Aruba', 'AW', 'ABW');
INSERT INTO countries (isocode, name, alfaisotwo, alfaisothree) VALUES ('036', 'Australia', 'AU', 'AUS');
INSERT INTO countries (isocode, name, alfaisotwo, alfaisothree) VALUES ('040', 'Austria', 'AT', 'AUT');
INSERT INTO countries (isocode, name, alfaisotwo, alfaisothree) VALUES ('031', 'Azerbaiyan', 'AZ', 'AZE');
INSERT INTO countries (isocode, name, alfaisotwo, alfaisothree) VALUES ('044', 'Bahamas', 'BS', 'BHS');
INSERT INTO countries (isocode, name, alfaisotwo, alfaisothree) VALUES ('050', 'Banglades', 'BD', 'BGD');
INSERT INTO countries (isocode, name, alfaisotwo, alfaisothree) VALUES ('052', 'Barbados', 'BB', 'BRB');
INSERT INTO countries (isocode, name, alfaisotwo, alfaisothree) VALUES ('048', 'Barein', 'BH', 'BHR');
INSERT INTO countries (isocode, name, alfaisotwo, alfaisothree) VALUES ('056', 'Belgica', 'BE', 'BEL');
INSERT INTO countries (isocode, name, alfaisotwo, alfaisothree) VALUES ('084', 'Belice', 'BZ', 'BLZ');
INSERT INTO countries (isocode, name, alfaisotwo, alfaisothree) VALUES ('204', 'Benin', 'BJ', 'BEN');
INSERT INTO countries (isocode, name, alfaisotwo, alfaisothree) VALUES ('060', 'Bermudas', 'BM', 'BMU');
INSERT INTO countries (isocode, name, alfaisotwo, alfaisothree) VALUES ('112', 'Bielorussia', 'BY', 'BLR');
INSERT INTO countries (isocode, name, alfaisotwo, alfaisothree) VALUES ('104', 'Birmania', 'MM', 'MMR');
INSERT INTO countries (isocode, name, alfaisotwo, alfaisothree) VALUES ('068', 'Bolivia', 'BO', 'BOL');
INSERT INTO countries (isocode, name, alfaisotwo, alfaisothree) VALUES ('070', 'Bosnia y Herzegovina', 'BA', 'BIH');
INSERT INTO countries (isocode, name, alfaisotwo, alfaisothree) VALUES ('072', 'Botsuana', 'BW', 'BWA');
INSERT INTO countries (isocode, name, alfaisotwo, alfaisothree) VALUES ('076', 'Brasil', 'BR', 'BRA');
INSERT INTO countries (isocode, name, alfaisotwo, alfaisothree) VALUES ('096', 'Brunei', 'BN', 'BRN');
INSERT INTO countries (isocode, name, alfaisotwo, alfaisothree) VALUES ('100', 'Bulgaria', 'BG', 'BGR');
INSERT INTO countries (isocode, name, alfaisotwo, alfaisothree) VALUES ('854', 'Burkina Faso', 'BF', 'BFA');
INSERT INTO countries (isocode, name, alfaisotwo, alfaisothree) VALUES ('108', 'Burundi', 'BI', 'BDI');
INSERT INTO countries (isocode, name, alfaisotwo, alfaisothree) VALUES ('064', 'Butan', 'BT', 'BTN');
INSERT INTO countries (isocode, name, alfaisotwo, alfaisothree) VALUES ('132', 'Cabo Verde', 'CV', 'CPV');
INSERT INTO countries (isocode, name, alfaisotwo, alfaisothree) VALUES ('116', 'Camboya', 'KH', 'KHM');
INSERT INTO countries (isocode, name, alfaisotwo, alfaisothree) VALUES ('120', 'Camerun', 'CM', 'CMR');
INSERT INTO countries (isocode, name, alfaisotwo, alfaisothree) VALUES ('124', 'Canada', 'CA', 'CAN');
INSERT INTO countries (isocode, name, alfaisotwo, alfaisothree) VALUES ('535', 'Caribe Neerlandes', 'BQ', 'BES');
INSERT INTO countries (isocode, name, alfaisotwo, alfaisothree) VALUES ('634', 'Catar', 'QA', 'QAT');
INSERT INTO countries (isocode, name, alfaisotwo, alfaisothree) VALUES ('148', 'Chad', 'TD', 'TCD');
INSERT INTO countries (isocode, name, alfaisotwo, alfaisothree) VALUES ('152', 'Chile', 'CL', 'CHL');
INSERT INTO countries (isocode, name, alfaisotwo, alfaisothree) VALUES ('156', 'China', 'CN', 'CHN');
INSERT INTO countries (isocode, name, alfaisotwo, alfaisothree) VALUES ('196', 'Chipre', 'CY', 'CYP');
INSERT INTO countries (isocode, name, alfaisotwo, alfaisothree) VALUES ('170', 'Colombia', 'CO', 'COL');
INSERT INTO countries (isocode, name, alfaisotwo, alfaisothree) VALUES ('174', 'Comoras', 'KM', 'COM');
INSERT INTO countries (isocode, name, alfaisotwo, alfaisothree) VALUES ('408', 'Corea del Norte', 'KP', 'PRK');
INSERT INTO countries (isocode, name, alfaisotwo, alfaisothree) VALUES ('410', 'Corea del Sur', 'KR', 'KOR');
INSERT INTO countries (isocode, name, alfaisotwo, alfaisothree) VALUES ('384', 'Costa de Marfil', 'CI', 'CIV');
INSERT INTO countries (isocode, name, alfaisotwo, alfaisothree) VALUES ('188', 'Costa Rica', 'CR', 'CRI');
INSERT INTO countries (isocode, name, alfaisotwo, alfaisothree) VALUES ('191', 'Croacia', 'HR', 'HRV');
INSERT INTO countries (isocode, name, alfaisotwo, alfaisothree) VALUES ('192', 'Cuba', 'CU', 'CUB');
INSERT INTO countries (isocode, name, alfaisotwo, alfaisothree) VALUES ('531', 'Curazao', 'CW', 'CUW');
INSERT INTO countries (isocode, name, alfaisotwo, alfaisothree) VALUES ('208', 'Dinamarca', 'DK', 'DNK');
INSERT INTO countries (isocode, name, alfaisotwo, alfaisothree) VALUES ('212', 'Dominica', 'DM', 'DMA');
INSERT INTO countries (isocode, name, alfaisotwo, alfaisothree) VALUES ('218', 'Ecuador', 'EC', 'ECU');
INSERT INTO countries (isocode, name, alfaisotwo, alfaisothree) VALUES ('818', 'Egipto', 'EG', 'EGY');
INSERT INTO countries (isocode, name, alfaisotwo, alfaisothree) VALUES ('222', 'El Salvador', 'SV', 'SLV');
INSERT INTO countries (isocode, name, alfaisotwo, alfaisothree) VALUES ('784', 'Emiratos Arabes Unidos', 'AE', 'ARE');
INSERT INTO countries (isocode, name, alfaisotwo, alfaisothree) VALUES ('232', 'Eritrea', 'ER', 'ERI');
INSERT INTO countries (isocode, name, alfaisotwo, alfaisothree) VALUES ('703', 'Eslovaquia', 'SK', 'SVK');
INSERT INTO countries (isocode, name, alfaisotwo, alfaisothree) VALUES ('705', 'Eslovenia', 'SI', 'SVN');
INSERT INTO countries (isocode, name, alfaisotwo, alfaisothree) VALUES ('724', 'Espana', 'ES', 'ESP');
INSERT INTO countries (isocode, name, alfaisotwo, alfaisothree) VALUES ('583', 'Estados Federados de Micronesia', 'FM', 'FSM');
INSERT INTO countries (isocode, name, alfaisotwo, alfaisothree) VALUES ('840', 'Estados Unidos', 'US', 'USA');
INSERT INTO countries (isocode, name, alfaisotwo, alfaisothree) VALUES ('233', 'Estonia', 'EE', 'EST');
INSERT INTO countries (isocode, name, alfaisotwo, alfaisothree) VALUES ('231', 'Etiopia', 'ET', 'ETH');
INSERT INTO countries (isocode, name, alfaisotwo, alfaisothree) VALUES ('608', 'Filipinas', 'PH', 'PHL');
INSERT INTO countries (isocode, name, alfaisotwo, alfaisothree) VALUES ('246', 'Finlandia', 'FI', 'FIN');
INSERT INTO countries (isocode, name, alfaisotwo, alfaisothree) VALUES ('242', 'Fiyi', 'FJ', 'FJI');
INSERT INTO countries (isocode, name, alfaisotwo, alfaisothree) VALUES ('250', 'Francia', 'FR', 'FRA');
INSERT INTO countries (isocode, name, alfaisotwo, alfaisothree) VALUES ('266', 'Gabon', 'GA', 'GAB');
INSERT INTO countries (isocode, name, alfaisotwo, alfaisothree) VALUES ('270', 'Gambia', 'GM', 'GMB');
INSERT INTO countries (isocode, name, alfaisotwo, alfaisothree) VALUES ('268', 'Georgia', 'GE', 'GEO');
INSERT INTO countries (isocode, name, alfaisotwo, alfaisothree) VALUES ('288', 'Ghana', 'GH', 'GHA');
INSERT INTO countries (isocode, name, alfaisotwo, alfaisothree) VALUES ('292', 'Gibraltar', 'GI', 'GIB');
INSERT INTO countries (isocode, name, alfaisotwo, alfaisothree) VALUES ('308', 'Granada', 'GD', 'GRD');
INSERT INTO countries (isocode, name, alfaisotwo, alfaisothree) VALUES ('300', 'Grecia', 'GR', 'GRC');
INSERT INTO countries (isocode, name, alfaisotwo, alfaisothree) VALUES ('304', 'Groenlandia', 'GL', 'GRL');
INSERT INTO countries (isocode, name, alfaisotwo, alfaisothree) VALUES ('312', 'Guadelupe', 'GP', 'GLP');
INSERT INTO countries (isocode, name, alfaisotwo, alfaisothree) VALUES ('316', 'Guam', 'GU', 'GUM');
INSERT INTO countries (isocode, name, alfaisotwo, alfaisothree) VALUES ('320', 'Guatemala', 'GT', 'GTM');
INSERT INTO countries (isocode, name, alfaisotwo, alfaisothree) VALUES ('254', 'Guayana Francesa', 'GF', 'GUF');
INSERT INTO countries (isocode, name, alfaisotwo, alfaisothree) VALUES ('831', 'Guernsey', 'GG', 'GGY');
INSERT INTO countries (isocode, name, alfaisotwo, alfaisothree) VALUES ('324', 'Guinea', 'GN', 'GIN');
INSERT INTO countries (isocode, name, alfaisotwo, alfaisothree) VALUES ('226', 'Guinea Ecuatorial', 'GQ', 'GNQ');
INSERT INTO countries (isocode, name, alfaisotwo, alfaisothree) VALUES ('624', 'Guinea-Bissau', 'GW', 'GNB');
INSERT INTO countries (isocode, name, alfaisotwo, alfaisothree) VALUES ('328', 'Guyana', 'GY', 'GUY');
INSERT INTO countries (isocode, name, alfaisotwo, alfaisothree) VALUES ('332', 'Haiti', 'HT', 'HTI');
INSERT INTO countries (isocode, name, alfaisotwo, alfaisothree) VALUES ('340', 'Honduras', 'HN', 'HND');
INSERT INTO countries (isocode, name, alfaisotwo, alfaisothree) VALUES ('344', 'Hong Kong', 'HK', 'HKG');
INSERT INTO countries (isocode, name, alfaisotwo, alfaisothree) VALUES ('348', 'Hungria', 'HU', 'HUN');
INSERT INTO countries (isocode, name, alfaisotwo, alfaisothree) VALUES ('352', 'Islandia', 'IS', 'ISL');
INSERT INTO countries (isocode, name, alfaisotwo, alfaisothree) VALUES ('356', 'India', 'IN', 'IND');
INSERT INTO countries (isocode, name, alfaisotwo, alfaisothree) VALUES ('360', 'Indonesia', 'ID', 'IDN');
INSERT INTO countries (isocode, name, alfaisotwo, alfaisothree) VALUES ('368', 'Irak', 'IQ', 'IRQ');
INSERT INTO countries (isocode, name, alfaisotwo, alfaisothree) VALUES ('364', 'Iran', 'IR', 'IRN');
INSERT INTO countries (isocode, name, alfaisotwo, alfaisothree) VALUES ('372', 'Irlanda', 'IE', 'IRL');
INSERT INTO countries (isocode, name, alfaisotwo, alfaisothree) VALUES ('833', 'Isla de Man', 'IM', 'IMN');
INSERT INTO countries (isocode, name, alfaisotwo, alfaisothree) VALUES ('162', 'Isla de Navidad', 'CX', 'CXR');
INSERT INTO countries (isocode, name, alfaisotwo, alfaisothree) VALUES ('574', 'Isla Norfolk', 'NF', 'NFK');
INSERT INTO countries (isocode, name, alfaisotwo, alfaisothree) VALUES ('136', 'Islas Caiman', 'KY', 'CYM');
INSERT INTO countries (isocode, name, alfaisotwo, alfaisothree) VALUES ('166', 'Islas Cocos', 'CC', 'CCK');
INSERT INTO countries (isocode, name, alfaisotwo, alfaisothree) VALUES ('184', 'Islas Cook', 'CK', 'COK');
INSERT INTO countries (isocode, name, alfaisotwo, alfaisothree) VALUES ('234', 'Islas Feroe', 'FO', 'FRO');
INSERT INTO countries (isocode, name, alfaisotwo, alfaisothree) VALUES ('239', 'Islas Georgias y Sandwich del Sur', 'GS', 'SGS');
INSERT INTO countries (isocode, name, alfaisotwo, alfaisothree) VALUES ('238', 'Islas Malvinas', 'FK', 'FLK');
INSERT INTO countries (isocode, name, alfaisotwo, alfaisothree) VALUES ('580', 'Islas Marianas del Norte', 'MP', 'MNP');
INSERT INTO countries (isocode, name, alfaisotwo, alfaisothree) VALUES ('584', 'Islas Marshall', 'MH', 'MHL');
INSERT INTO countries (isocode, name, alfaisotwo, alfaisothree) VALUES ('612', 'Islas Pitcairn', 'PN', 'PCN');
INSERT INTO countries (isocode, name, alfaisotwo, alfaisothree) VALUES ('090', 'Islas Salomon', 'SB', 'SLB');
INSERT INTO countries (isocode, name, alfaisotwo, alfaisothree) VALUES ('796', 'Islas Turcas y Caicos', 'TC', 'TCA');
INSERT INTO countries (isocode, name, alfaisotwo, alfaisothree) VALUES ('092', 'Islas Virgenes Britanicas', 'VG', 'VGB');
INSERT INTO countries (isocode, name, alfaisotwo, alfaisothree) VALUES ('850', 'Islas Virgenes de los Estados Unidos', 'VI', 'VIR');
INSERT INTO countries (isocode, name, alfaisotwo, alfaisothree) VALUES ('376', 'Israel', 'IL', 'ISR');
INSERT INTO countries (isocode, name, alfaisotwo, alfaisothree) VALUES ('380', 'Italia', 'IT', 'ITA');
INSERT INTO countries (isocode, name, alfaisotwo, alfaisothree) VALUES ('388', 'Jamaica', 'JM', 'JAM');
INSERT INTO countries (isocode, name, alfaisotwo, alfaisothree) VALUES ('392', 'Japon', 'JP', 'JPN');
INSERT INTO countries (isocode, name, alfaisotwo, alfaisothree) VALUES ('832', 'Jersey', 'JE', 'JEY');
INSERT INTO countries (isocode, name, alfaisotwo, alfaisothree) VALUES ('400', 'Jordania', 'JO', 'JOR');
INSERT INTO countries (isocode, name, alfaisotwo, alfaisothree) VALUES ('398', 'Kazajistan', 'KZ', 'KAZ');
INSERT INTO countries (isocode, name, alfaisotwo, alfaisothree) VALUES ('404', 'Kenia', 'KE', 'KEN');
INSERT INTO countries (isocode, name, alfaisotwo, alfaisothree) VALUES ('417', 'Kirguistan', 'KG', 'KGZ');
INSERT INTO countries (isocode, name, alfaisotwo, alfaisothree) VALUES ('296', 'Kiribati', 'KI', 'KIR');
INSERT INTO countries (isocode, name, alfaisotwo, alfaisothree) VALUES ('153', 'Kosovo', 'XK', 'XKX');
INSERT INTO countries (isocode, name, alfaisotwo, alfaisothree) VALUES ('414', 'Kuweit', 'KW', 'KWT');
INSERT INTO countries (isocode, name, alfaisotwo, alfaisothree) VALUES ('418', 'Laos', 'LA', 'LAO');
INSERT INTO countries (isocode, name, alfaisotwo, alfaisothree) VALUES ('426', 'Lesoto', 'LS', 'LSO');
INSERT INTO countries (isocode, name, alfaisotwo, alfaisothree) VALUES ('428', 'Letonia', 'LV', 'LVA');
INSERT INTO countries (isocode, name, alfaisotwo, alfaisothree) VALUES ('422', 'Libano', 'LB', 'LBN');
INSERT INTO countries (isocode, name, alfaisotwo, alfaisothree) VALUES ('430', 'Liberia', 'LR', 'LBR');
INSERT INTO countries (isocode, name, alfaisotwo, alfaisothree) VALUES ('434', 'Libia', 'LY', 'LBY');
INSERT INTO countries (isocode, name, alfaisotwo, alfaisothree) VALUES ('438', 'Liechtenstein', 'LI', 'LIE');
INSERT INTO countries (isocode, name, alfaisotwo, alfaisothree) VALUES ('440', 'Lituania', 'LT', 'LTU');
INSERT INTO countries (isocode, name, alfaisotwo, alfaisothree) VALUES ('442', 'Luxemburgo', 'LU', 'LUX');
INSERT INTO countries (isocode, name, alfaisotwo, alfaisothree) VALUES ('446', 'Macao', 'MO', 'MAC');
INSERT INTO countries (isocode, name, alfaisotwo, alfaisothree) VALUES ('807', 'Macedonia del Norte', 'MK', 'MKD');
INSERT INTO countries (isocode, name, alfaisotwo, alfaisothree) VALUES ('450', 'Madagascar', 'MG', 'MDG');
INSERT INTO countries (isocode, name, alfaisotwo, alfaisothree) VALUES ('458', 'Malasia', 'MY', 'MYS');
INSERT INTO countries (isocode, name, alfaisotwo, alfaisothree) VALUES ('454', 'Malawi', 'MW', 'MWI');
INSERT INTO countries (isocode, name, alfaisotwo, alfaisothree) VALUES ('462', 'Maldivas', 'MV', 'MDV');
INSERT INTO countries (isocode, name, alfaisotwo, alfaisothree) VALUES ('466', 'Mali', 'ML', 'MLI');
INSERT INTO countries (isocode, name, alfaisotwo, alfaisothree) VALUES ('470', 'Malta', 'MT', 'MLT');
INSERT INTO countries (isocode, name, alfaisotwo, alfaisothree) VALUES ('504', 'Marruecos', 'MA', 'MAR');
INSERT INTO countries (isocode, name, alfaisotwo, alfaisothree) VALUES ('474', 'Martinica', 'MQ', 'MTQ');
INSERT INTO countries (isocode, name, alfaisotwo, alfaisothree) VALUES ('480', 'Mauricio', 'MU', 'MUS');
INSERT INTO countries (isocode, name, alfaisotwo, alfaisothree) VALUES ('478', 'Mauritania', 'MR', 'MRT');
INSERT INTO countries (isocode, name, alfaisotwo, alfaisothree) VALUES ('175', 'Mayotte', 'YT', 'MYT');
INSERT INTO countries (isocode, name, alfaisotwo, alfaisothree) VALUES ('484', 'Mexico', 'MX', 'MEX');
INSERT INTO countries (isocode, name, alfaisotwo, alfaisothree) VALUES ('498', 'Moldavia', 'MD', 'MDA');
INSERT INTO countries (isocode, name, alfaisotwo, alfaisothree) VALUES ('492', 'Monaco', 'MC', 'MCO');
INSERT INTO countries (isocode, name, alfaisotwo, alfaisothree) VALUES ('496', 'Mongolia', 'MN', 'MNG');
INSERT INTO countries (isocode, name, alfaisotwo, alfaisothree) VALUES ('499', 'Montenegro', 'ME', 'MNE');
INSERT INTO countries (isocode, name, alfaisotwo, alfaisothree) VALUES ('500', 'Montserrat', 'MS', 'MSR');
INSERT INTO countries (isocode, name, alfaisotwo, alfaisothree) VALUES ('508', 'Mozambique', 'MZ', 'MOZ');
INSERT INTO countries (isocode, name, alfaisotwo, alfaisothree) VALUES ('516', 'Namibia', 'NA', 'NAM');
INSERT INTO countries (isocode, name, alfaisotwo, alfaisothree) VALUES ('520', 'Nauru', 'NR', 'NRU');
INSERT INTO countries (isocode, name, alfaisotwo, alfaisothree) VALUES ('524', 'Nepal', 'NP', 'NPL');
INSERT INTO countries (isocode, name, alfaisotwo, alfaisothree) VALUES ('558', 'Nicaragua', 'NI', 'NIC');
INSERT INTO countries (isocode, name, alfaisotwo, alfaisothree) VALUES ('562', 'Niger', 'NE', 'NER');
INSERT INTO countries (isocode, name, alfaisotwo, alfaisothree) VALUES ('566', 'Nigeria', 'NG', 'NGA');
INSERT INTO countries (isocode, name, alfaisotwo, alfaisothree) VALUES ('570', 'Niue', 'NU', 'NIU');
INSERT INTO countries (isocode, name, alfaisotwo, alfaisothree) VALUES ('578', 'Noruega', 'NO', 'NOR');
INSERT INTO countries (isocode, name, alfaisotwo, alfaisothree) VALUES ('540', 'Nueva Caledonia', 'NC', 'NCL');
INSERT INTO countries (isocode, name, alfaisotwo, alfaisothree) VALUES ('554', 'Nueva Zelanda', 'NZ', 'NZL');
INSERT INTO countries (isocode, name, alfaisotwo, alfaisothree) VALUES ('512', 'Oman', 'OM', 'OMN');
INSERT INTO countries (isocode, name, alfaisotwo, alfaisothree) VALUES ('528', 'Paises Bajos', 'NL', 'NLD');
INSERT INTO countries (isocode, name, alfaisotwo, alfaisothree) VALUES ('586', 'Pakistan', 'PK', 'PAK');
INSERT INTO countries (isocode, name, alfaisotwo, alfaisothree) VALUES ('585', 'Palaos', 'PW', 'PLW');
INSERT INTO countries (isocode, name, alfaisotwo, alfaisothree) VALUES ('275', 'Palestina', 'PS', 'PSE');
INSERT INTO countries (isocode, name, alfaisotwo, alfaisothree) VALUES ('591', 'Panama', 'PA', 'PAN');
INSERT INTO countries (isocode, name, alfaisotwo, alfaisothree) VALUES ('598', 'Papua Nueva Guinea', 'PG', 'PNG');
INSERT INTO countries (isocode, name, alfaisotwo, alfaisothree) VALUES ('600', 'Paraguay', 'PY', 'PRY');
INSERT INTO countries (isocode, name, alfaisotwo, alfaisothree) VALUES ('604', 'Peru', 'PE', 'PER');
INSERT INTO countries (isocode, name, alfaisotwo, alfaisothree) VALUES ('258', 'Polinesia Francesa', 'PF', 'PYF');
INSERT INTO countries (isocode, name, alfaisotwo, alfaisothree) VALUES ('616', 'Polonia', 'PL', 'POL');
INSERT INTO countries (isocode, name, alfaisotwo, alfaisothree) VALUES ('620', 'Portugal', 'PT', 'PRT');
INSERT INTO countries (isocode, name, alfaisotwo, alfaisothree) VALUES ('630', 'Puerto Rico', 'PR', 'PRI');
INSERT INTO countries (isocode, name, alfaisotwo, alfaisothree) VALUES ('826', 'Reino Unido', 'GB', 'GBR');
INSERT INTO countries (isocode, name, alfaisotwo, alfaisothree) VALUES ('732', 'Republica Arabe Saharaui Democratica', 'EH', 'ESH');
INSERT INTO countries (isocode, name, alfaisotwo, alfaisothree) VALUES ('140', 'Republica Centroafricana', 'CF', 'CAF');
INSERT INTO countries (isocode, name, alfaisotwo, alfaisothree) VALUES ('203', 'Republica Checa', 'CZ', 'CZE');
INSERT INTO countries (isocode, name, alfaisotwo, alfaisothree) VALUES ('178', 'Republica del Congo', 'CG', 'COG');
INSERT INTO countries (isocode, name, alfaisotwo, alfaisothree) VALUES ('180', 'Republica Democratica del Congo', 'CD', 'COD');
INSERT INTO countries (isocode, name, alfaisotwo, alfaisothree) VALUES ('214', 'Republica Dominicana', 'DO', 'DOM');
INSERT INTO countries (isocode, name, alfaisotwo, alfaisothree) VALUES ('638', 'Reunion', 'RE', 'REU');
INSERT INTO countries (isocode, name, alfaisotwo, alfaisothree) VALUES ('646', 'Ruanda', 'RW', 'RWA');
INSERT INTO countries (isocode, name, alfaisotwo, alfaisothree) VALUES ('642', 'Rumania', 'RO', 'ROU');
INSERT INTO countries (isocode, name, alfaisotwo, alfaisothree) VALUES ('643', 'Rusia', 'RU', 'RUS');
INSERT INTO countries (isocode, name, alfaisotwo, alfaisothree) VALUES ('882', 'Samoa', 'WS', 'WSM');
INSERT INTO countries (isocode, name, alfaisotwo, alfaisothree) VALUES ('016', 'Samoa Americana', 'AS', 'ASM');
INSERT INTO countries (isocode, name, alfaisotwo, alfaisothree) VALUES ('652', 'San Bartolome', 'BL', 'BLM');
INSERT INTO countries (isocode, name, alfaisotwo, alfaisothree) VALUES ('659', 'San Cristobal y Nieves', 'KN', 'KNA');
INSERT INTO countries (isocode, name, alfaisotwo, alfaisothree) VALUES ('674', 'San Marino', 'SM', 'SMR');
INSERT INTO countries (isocode, name, alfaisotwo, alfaisothree) VALUES ('534', 'San Martin', 'MF', 'MAF');
INSERT INTO countries (isocode, name, alfaisotwo, alfaisothree) VALUES ('666', 'San Pedro y Miquelon', 'PM', 'SPM');
INSERT INTO countries (isocode, name, alfaisotwo, alfaisothree) VALUES ('670', 'San Vicente y las Granadinas', 'VC', 'VCT');
INSERT INTO countries (isocode, name, alfaisotwo, alfaisothree) VALUES ('662', 'Santa Lucia', 'LC', 'LCA');
INSERT INTO countries (isocode, name, alfaisotwo, alfaisothree) VALUES ('678', 'Santo Tome y Principe', 'ST', 'STP');
INSERT INTO countries (isocode, name, alfaisotwo, alfaisothree) VALUES ('686', 'Senegal', 'SN', 'SEN');
INSERT INTO countries (isocode, name, alfaisotwo, alfaisothree) VALUES ('688', 'Serbia', 'RS', 'SRB');
INSERT INTO countries (isocode, name, alfaisotwo, alfaisothree) VALUES ('690', 'Seychelles', 'SC', 'SYC');
INSERT INTO countries (isocode, name, alfaisotwo, alfaisothree) VALUES ('694', 'Sierra Leona', 'SL', 'SLE');
INSERT INTO countries (isocode, name, alfaisotwo, alfaisothree) VALUES ('702', 'Singapur', 'SG', 'SGP');
INSERT INTO countries (isocode, name, alfaisotwo, alfaisothree) VALUES ('654', 'Sint Helena, Ascension and Tristan da Cunha', 'SH', 'SHN');
INSERT INTO countries (isocode, name, alfaisotwo, alfaisothree) VALUES ('663', 'Sint-Maarten', 'SX', 'SXM');
INSERT INTO countries (isocode, name, alfaisotwo, alfaisothree) VALUES ('760', 'Siria', 'SY', 'SYR');
INSERT INTO countries (isocode, name, alfaisotwo, alfaisothree) VALUES ('706', 'Somalia', 'SO', 'SOM');
INSERT INTO countries (isocode, name, alfaisotwo, alfaisothree) VALUES ('144', 'Sri Lanka', 'LK', 'LKA');
INSERT INTO countries (isocode, name, alfaisotwo, alfaisothree) VALUES ('748', 'eSwatini', 'SZ', 'SWZ');
INSERT INTO countries (isocode, name, alfaisotwo, alfaisothree) VALUES ('710', 'Sudafrica', 'ZA', 'ZAF');
INSERT INTO countries (isocode, name, alfaisotwo, alfaisothree) VALUES ('729', 'Sudan', 'SD', 'SDN');
INSERT INTO countries (isocode, name, alfaisotwo, alfaisothree) VALUES ('728', 'Sudan del Sur', 'SS', 'SSD');
INSERT INTO countries (isocode, name, alfaisotwo, alfaisothree) VALUES ('752', 'Suecia', 'SE', 'SWE');
INSERT INTO countries (isocode, name, alfaisotwo, alfaisothree) VALUES ('756', 'Suiza', 'CH', 'CHE');
INSERT INTO countries (isocode, name, alfaisotwo, alfaisothree) VALUES ('740', 'Surinam', 'SR', 'SUR');
INSERT INTO countries (isocode, name, alfaisotwo, alfaisothree) VALUES ('764', 'Tailandia', 'TH', 'THA');
INSERT INTO countries (isocode, name, alfaisotwo, alfaisothree) VALUES ('158', 'Taiwan', 'TW', 'TWN');
INSERT INTO countries (isocode, name, alfaisotwo, alfaisothree) VALUES ('834', 'Tanzania', 'TZ', 'TZA');
INSERT INTO countries (isocode, name, alfaisotwo, alfaisothree) VALUES ('762', 'Tayikistan', 'TJ', 'TJK');
INSERT INTO countries (isocode, name, alfaisotwo, alfaisothree) VALUES ('086', 'Territorio Britanico del Oceano Indico', 'IO', 'IOT');
INSERT INTO countries (isocode, name, alfaisotwo, alfaisothree) VALUES ('260', 'Tierras Australes y Antarticas Francesas', 'TF', 'ATF');
INSERT INTO countries (isocode, name, alfaisotwo, alfaisothree) VALUES ('626', 'Timor Oriental', 'TL', 'TLS');
INSERT INTO countries (isocode, name, alfaisotwo, alfaisothree) VALUES ('768', 'Togo', 'TG', 'TGO');
INSERT INTO countries (isocode, name, alfaisotwo, alfaisothree) VALUES ('772', 'Tokelau', 'TK', 'TKL');
INSERT INTO countries (isocode, name, alfaisotwo, alfaisothree) VALUES ('776', 'Tonga', 'TO', 'TON');
INSERT INTO countries (isocode, name, alfaisotwo, alfaisothree) VALUES ('780', 'Trinidad y Tobago', 'TT', 'TTO');
INSERT INTO countries (isocode, name, alfaisotwo, alfaisothree) VALUES ('788', 'Tunez', 'TN', 'TUN');
INSERT INTO countries (isocode, name, alfaisotwo, alfaisothree) VALUES ('795', 'Turkmenistan', 'TM', 'TKM');
INSERT INTO countries (isocode, name, alfaisotwo, alfaisothree) VALUES ('792', 'Turquia', 'TR', 'TUR');
INSERT INTO countries (isocode, name, alfaisotwo, alfaisothree) VALUES ('798', 'Tuvalu', 'TV', 'TUV');
INSERT INTO countries (isocode, name, alfaisotwo, alfaisothree) VALUES ('804', 'Ucrania', 'UA', 'UKR');
INSERT INTO countries (isocode, name, alfaisotwo, alfaisothree) VALUES ('800', 'Uganda', 'UG', 'UGA');
INSERT INTO countries (isocode, name, alfaisotwo, alfaisothree) VALUES ('858', 'Uruguay', 'UY', 'URY');
INSERT INTO countries (isocode, name, alfaisotwo, alfaisothree) VALUES ('860', 'Uzbekistan', 'UZ', 'UZB');
INSERT INTO countries (isocode, name, alfaisotwo, alfaisothree) VALUES ('548', 'Vanuatu', 'VU', 'VUT');
INSERT INTO countries (isocode, name, alfaisotwo, alfaisothree) VALUES ('336', 'Vaticano', 'VA', 'VAT');
INSERT INTO countries (isocode, name, alfaisotwo, alfaisothree) VALUES ('862', 'Venezuela', 'VE', 'VEN');
INSERT INTO countries (isocode, name, alfaisotwo, alfaisothree) VALUES ('704', 'Vietnam', 'VN', 'VNM');
INSERT INTO countries (isocode, name, alfaisotwo, alfaisothree) VALUES ('876', 'Wallis y Futuna', 'WF', 'WLF');
INSERT INTO countries (isocode, name, alfaisotwo, alfaisothree) VALUES ('887', 'Yemen', 'YE', 'YEM');
INSERT INTO countries (isocode, name, alfaisotwo, alfaisothree) VALUES ('262', 'Yibuti', 'DJ', 'DJI');
INSERT INTO countries (isocode, name, alfaisotwo, alfaisothree) VALUES ('894', 'Zambia', 'ZM', 'ZMB');
INSERT INTO countries (isocode, name, alfaisotwo, alfaisothree) VALUES ('716', 'Zimbabwe', 'ZW', 'ZWE');

SELECT COUNT(*) FROM countries;
